title: PKP Documentation Hub
plugins:
  - jekyll-seo-tag
  - jekyll-relative-links
  - jekyll-optional-front-matter
  - jekyll-default-layout
  - jekyll-titles-from-headings
  - jekyll-readme-index
defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "book"
pkp_search:
  exclude_file_types:
    - '.scss'
    - '.css'
    - '.js'
  exclude_titles:
    - 'Summary'
  exclude_paths:
    - 'SUMMARY.md'
