siteAbout: "The [Public Knowledge Project](https://pkp.sfu.ca) is a multi-university initiative to improve the quality and reach of scholarly publishing."
linkBackToDocs: "Back to [all documentation](/)."
skipToSummary: "Jump to table of contents"
skipToSummary: "Toggle Menu"
searchLabel: Search
searchPlaceholder: Search everything
visitForum: "Visit our [community forum](https://forum.pkp.sfu.ca) to meet hundreds of editors, publishers and journal managers."
devVersion: "Warning: In Development"
devVersionDescription: "This document describes features or capabilities that have not yet been released to the public. This information is provided as advanced notice for what we plan to be included in future versions. But the details here may change without warning."
improveLink: "Improve this page"
improveLinkBaseUrl: "https://github.com/pkp/pkp-docs/edit/master/"
navContrib:
  title: Community
  items:
    - "[Documentation Interest Group](https://pkp.sfu.ca/documentation-interest-group/)"
    - "[Contributing Documentation](/contributing)"
    - "[Translating Guide](/translating-guide/)"
    - "[Community Forum](https://forum.pkp.sfu.ca)"
navAbout:
  title: About
  items:
    - "[Public Knowledge Project](https://pkp.sfu.ca)"
    - "[PKP&#124;Publishing Services](https://pkpservices.sfu.ca/)"
